pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('complete') {
            steps {
                sh "echo complete"
            }
        }
        stage('complete-multi1') {
            steps {
                sh "echo completed multi1"
            }
        }
    }
}
